### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstname": "Test",
  "lastname": "User",
  "email": "test@example.com",
  "password": "password123"
}

### Register a new admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstname": "Admin",
  "lastname": "User",
  "email": "admin@example.com",
  "password": "adminpassword123",
  "role": "admin"
}

### Login as user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login as admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword123"
}